version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chat
    networks:
      - nodejs-network

  mongodb:
    image: mongo:latest
    container_name: nodejs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge

volumes:
  mongodb_data: 